### ISSUE TITLE
colours / title for the drawer

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-header-services#1]
![drawer](https://cloud.githubusercontent.com/assets/68009/17097542/173b784a-5256-11e6-85bd-bbea1f6eb709.gif)

The drawer needs colour choices, it currently only has one theme (the salmon pink one)
Also not sure what the title element of the draw should be...? Maybe it shouldn't have one at all?

**Comment by gvonkoss** [comment]
Closing as this will be addressed with the new brand component
