### ISSUE TITLE
[FEATURE REQUEST] Toggle whether opening a burger menu collapses all list items or not by default

### ISSUE THREAD

**Issue by B-0-B-B-Y** [Financial-Times/o-header-services#102]
Feature Request

## What

In the event that the website structure is such that there are parent pages which each have child pages, when a user is currently on a child page and is on a mobile device and opens up the menu, the parent of the child page should be expanded by default, so that it can be shown to the user exactly where they are in the hierarchy of the website.
## Details

This arose as part of a design request for the new fDi Frontend stack. The menu on mobile needs to behave as described above. Please refer to the screenshot below.
![image](https://user-images.githubusercontent.com/27875954/58882926-58f33280-86d5-11e9-98d9-4f43ea5e6b81.png)

**Comment by notlee** [comment]
This was released as the default behavior in v3.3.0.
