### ISSUE TITLE
Incorrect nav state when page initially loads 

### ISSUE THREAD

**Issue by ryanolee** [Financial-Times/o-header-services#104]
Bug ticket in relation to: https://github.com/Financial-Times/o-header-services/pull/103/files

## What
Top level nav items have `aria-expanded="true"` set on them on initial page load when viewing in desktop viewports.

## Details
Currently when using o-header-services v3.3.0 when the page firsts loads in a desktop viewport size, if the page you are on matches a nav item, `aria-expanded="true"` is accidentally sent. Note that the arrow is the wrong way round on the matching nav item.

This issue can be seen here when the page is first loaded https://fdi-router-test.herokuapp.com/promote-your-location

![image](https://user-images.githubusercontent.com/17767073/59448781-c998fe00-8dfd-11e9-82ae-e79919b9bae7.png)

**Comment by notlee** [comment]
Hey, as mentioned in Slack
> [...] thanks for creating a detailed issue 🙂 I had a look at o-header-services and couldn’t see an obvious cause. I noticed with JS disabled the attribute is still wrong, and think I’ve tracked the issue down to [this fdi jsx template](https://github.com/Financial-Times/fdi-frontend/blob/master/components/header/primary-nav/NavItem.jsx#L313).

So I'm going to close this issue, but let me know if that's not the case!
