### ISSUE TITLE
Navigation dropdown menu open after screen orientation change

### ISSUE THREAD

**Issue by tomiplaz** [Financial-Times/o-header-services#106]
Type: A bug report

## What

Navigation dropdown menu is open when screen orientation changes from portrait to landscape on devices that have mobile/burger menu in portrait mode and non-mobile/regular menu in landscape mode.

## Details

Expected behaviour is not having dropdown menu open when screen orientation change happens (for devices described in the above paragraph).

To reproduce, go to https://www.ft.com/__origami/service/build/v2/demos/o-header-services@3.3.0/drop-down-navigation?brand=master and set the resolution to 375 (W) * 740 (H). Then change the orientation / rotate the viewport and notice that dropdown menu is open.

I'm using Firefox 67.0.4 on Mac.

Screenshots below.

Before orientation change (portrait mode, mobile/burger menu):
![image](https://user-images.githubusercontent.com/8911307/60089142-c8d66500-9737-11e9-8d7f-151c2a0da8ac.png)

After orientation change (landscape mode, non-mobile/regular menu):
![image](https://user-images.githubusercontent.com/8911307/60089217-edcad800-9737-11e9-8b3a-cfba1e217beb.png)

**Comment by notlee** [comment]
Thanks Tom, I've opened a PR to address this: https://github.com/Financial-Times/o-header-services/issues/106

**Comment by notlee** [comment]
Fixed in v3.3.1 :)

**Comment by tomiplaz** [comment]
> _Oops, sorry, I defaulted to abbreviating your name without thinking. Do you prefer to go by your full name?_

Abbreviating it is completely fine! :) Lots of the time I introduce myself as Tom, so it's all good!

Thanks for the fix!
