### ISSUE TITLE
Theme for internally-facing services

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/o-header-services#12]
It's not particularly important, but we could consider adding a theme for internal customers.  Possibly even divide by audience (Editorial Tools, Engineering Tools etc)

**Comment by alicebartlett** [comment]
The default theme (grey) was intended for this purpose, do you think it needs something more?

**Comment by lucas42** [comment]
The default theme looks fine - might be worth making its purpose clear in the docs.  Currently it just says "If you're creating a product that isn't within B2B or B2C please contact Origami."

**Comment by alicebartlett** [comment]
#15
