### ISSUE TITLE
Button element should not be a child of unordered list

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-header-services#142]
This is a bug.

## What

The markup pattern used to create dropdown menus places a `<button>` element as a direct descendant of an unordered list.

## Details

The only content allowed within an unordered list are list items, `<script>` and `<template>` elements according to the HTML spec.

Because the markup is invalid it may be error-corrected by the browser which could result in inconsistencies as this behaviour is not specified. Some browsers may eject the button element from the list and others may not.

- https://github.com/Financial-Times/o-header-services/blob/master/demos/src/header.mustache#L46
- https://github.com/Financial-Times/o-header-services/blob/master/demos/src/header.mustache#L68

## Additional information

From a quick look I cannot see any JS or CSS _explicitly_ attached to these buttons.

**Comment by notlee** [comment]
Thanks for finding this and letting us know. I've opened a PR to add the missing `li` to our demos, and will let users I'm aware of outside of O&R to update their markup when it's released.
https://github.com/Financial-Times/o-header-services/pull/143
