### ISSUE TITLE
Inconsistent border styles on dropdown toggles

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-header-services#150]
Type: Minor bug

## What

When viewed on a small screen the primary links have some inconsistent border styles applied to different elements which does not look very nice.

## Details

As seen in the screenshots below the expand dropdown button has no top border but 1px bottom border, either leaving no border and/or a double border.

Demo with master brand:

<img width="640" alt="Screenshot 2020-07-20 at 16 55 11" src="https://user-images.githubusercontent.com/271645/87959557-ff052600-caaa-11ea-9aa8-9ca492a83cd9.png">

App using the internal brand:

<img width="640" alt="Screenshot 2020-07-20 at 17 02 56" src="https://user-images.githubusercontent.com/271645/87959602-0f1d0580-caab-11ea-859d-3d30fd4419b6.png">

**Comment by notlee** [comment]
thanks for reporting, we'll take a look :)
