### ISSUE TITLE
Accessibility: Collapsed dropdown menus should not contain focusable elements.

### ISSUE THREAD

**Issue by nickcolley** [Financial-Times/o-header-services#152]
When a menu is closed you can tab to the hidden elements but they are not visible.

We should consider using `display: none` or `[hidden]` when they are closed rather than visually hidden classes.

https://github.com/Financial-Times/o-header-services/blob/master/src/scss/_drop-down.scss#L89

Noticed this one running axe manually:

https://dequeuniversity.com/rules/axe/3.5/aria-hidden-focus?application=AxeChrome

**Comment by notlee** [comment]
Thanks for reporting @nickcolley! As part of this work we should [add a pa11y demo](https://github.com/Financial-Times/o-header-services/issues/153) so axe catches future issues
