### ISSUE TITLE
Require $system_code variable be set by consumers of this component

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-header-services#46]
We have a lot of origami-image-service requests with source=o-icons, which is actually not useful as we don't know who the real source is. E.G. Is it HTSI/FT/NAR/ScoutAsia?

This is due to the fact that the origami components hardcode a source value in their scss. E.G. https://github.com/Financial-Times/o-header-services/blob/10a32e0ea858d3d95b12cf0841b716cb2bc07cb8/src/scss/_variables.scss#L10

I'm thinking when we introduce source= to the Origami-Build-Service, we update the origami components to require users pass in a $source or $system_code variable in order to use them. We can then use the $system_code/$source as the value passed to the origami-image-service URLs within the scss.

Waiting on Financial-Times/origami-build-service#67

**Comment by gvonkoss** [comment]
@JakeChampion is this still relevant? Or have we changed the approach and can we close this issue?

**Comment by notlee** [comment]
Addressed in, closing to keep track of solved breaking issues https://github.com/Financial-Times/o-header-services/pull/113
