### ISSUE TITLE
Sass Variable to adjust spacing between caret and drop down

### ISSUE THREAD

**Issue by adam-djangophi** [Financial-Times/o-header-services#70]
[type]:  A feature request

## What

Provide and overridable sass variable which allows us to adjust or remove the spacing between the text and the caret in the drop-down selector 

## Details

We are using the white-label 3.0 version which was intended to more closely resemble the new fDI intelligence designs. In this particular the spacing between the caret and the text is too large and we're wondering if this could be overridden with a sass variable.

## Additional information

Point 1 in [doc](https://docs.google.com/document/d/1Nct0sAETHLDES1GQLnUx2Og82aOSGbm9DfIzxY4h7UU/edit)

**Comment by notlee** [comment]
We added `primary-nav-item-horizontal-padding` for this, as well as [other new brand variables](https://github.com/Financial-Times/o-header-services/issues/73) :)
