### ISSUE TITLE
Text click to trigger drop-down

### ISSUE THREAD

**Issue by adam-djangophi** [Financial-Times/o-header-services#71]
[type]:  A feature request?

## What
Is it possible to have a variant of the drop down which triggers the drop down via text click as well as the caret click.

## Details
Currently the dropdown only triggers when the caret is pressed. 

## Additional Details

Point 2 on [doc](https://docs.google.com/document/d/1Nct0sAETHLDES1GQLnUx2Og82aOSGbm9DfIzxY4h7UU/edit)

**Comment by notlee** [comment]
We'd like to avoid the complexities and potential accessibility pitfalls of maintaining both options. Tom has updated his designs to account for having a link as well as a dropdown. Let us know if you have any questions/issues  :)
