### ISSUE TITLE
keep nav menu on same line when container is resized

### ISSUE THREAD

**Issue by adam-djangophi** [Financial-Times/o-header-services#72]
[type]:  A feature request?

## What
is it possible to have them nav menu remain on the same line in a horizontally scrollable container when the window is resized.

## Details
Currently when the screen size changes the nav elements wrap onto a new line

## Additional Details

Point 3 on [doc](https://docs.google.com/document/d/1Nct0sAETHLDES1GQLnUx2Og82aOSGbm9DfIzxY4h7UU/edit)

**Comment by notlee** [comment]
Thanks for writing out these issues. :) A scroll-able container might be the better approach but potentially significantly more work for a one-off use case. Instead, to meet Tom's designs, we've added the ability to customise the breakpoint at which the drawer appears.

To update the drawer breakpoint set [drawer-breakpoint](https://github.com/Financial-Times/o-header-services#sass) option when including `o-header-services`.

E.g.
```
@include oHeaderServices($opts: (
	'types': ('primary-nav'),
	'features': ('drop-down'),
        'drawer-breakpoint': L,
	'logo': 'origami'
))
```

**Comment by notlee** [comment]
Let us know if you have any questions ☝️
