### ISSUE TITLE
Provide sass variables to help theme the dropdown menu

### ISSUE THREAD

**Issue by adam-djangophi** [Financial-Times/o-header-services#73]
[type]:  A feature request?

## What
Is it possible to have to Sass Variables that we can use which will override the background color, text, color, and border, and on-hover text-color of the drop-down menu that appears.

## Details
We need to make design changes to the appearance of the drop down which appears.

## Additional Details

Points 4 & 5 on [doc](https://docs.google.com/document/d/1Nct0sAETHLDES1GQLnUx2Og82aOSGbm9DfIzxY4h7UU/edit)

**Comment by notlee** [comment]
Thanks, we've improved this in `^3.1.0` 👍 Working with Tom, the brand variables are now:

```
// current
top-text
top-background
nav-text
nav-background
nav-border
nav-hover-background
nav-underline-color
arrow-icon-color
arrow-icon-hover-color
button-hover-color

// plus these new variables
text-hover-color
drawer-background
drawer-button-background
drawer-text-hover-color
drawer-nav-hover-background
primary-nav-item-horizontal-padding
```
