### ISSUE TITLE
Adjust initial hidden position of dropdown menu

### ISSUE THREAD

**Issue by adam-djangophi** [Financial-Times/o-header-services#74]
[type]: A feature request 

## What
The initial hidden position of the drop down has `transform: translateY(-100%);` set. It would be great if we could set this to 0 with a sass variable as we are getting z-index issues when it scrolls into view when triggered.

## Details
When the menu is toggled into it scrolls from above and causes some z-index issues with the rows above it.

## Additional information
Point 6 on [doc](https://docs.google.com/document/d/1Nct0sAETHLDES1GQLnUx2Og82aOSGbm9DfIzxY4h7UU/edit)

**Comment by notlee** [comment]
Thanks, we've solved this in `^3.1.0` 👍
